# fly.toml app configuration file generated for proud-wildflower-6917 on 2023-10-07T21:56:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proud-wildflower-6917"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
